import { User, Student, Subject, AttendanceRecord } from '../models';

export const MOCK_USERS: User[] = [
  // Instructors
  {
    id: 'inst-001',
    email: 'sarah.wilson@university.edu',
    password: 'instructor123',
    role: 'instructor',
    name: 'Dr. Sarah Wilson',
    avatar: 'https://via.placeholder.com/100?text=Sarah',
  },
  {
    id: 'inst-002',
    email: 'john.doe@university.edu',
    password: 'instructor123',
    role: 'instructor',
    name: 'Prof. John Doe',
    avatar: 'https://via.placeholder.com/100?text=John',
  },
  // Admin
  {
    id: 'admin-001',
    email: 'admin@ustp.edu',
    password: 'admin123',
    role: 'admin',
    name: 'System Admin',
    avatar: 'https://via.placeholder.com/100?text=Admin',
  },
  // Students
  {
    id: 'student-001',
    email: 'alice.johnson@university.edu',
    password: 'student123',
    role: 'student',
    name: 'Alice Johnson',
    avatar: 'https://via.placeholder.com/100?text=Alice',
  },
  {
    id: 'student-002',
    email: 'bob.smith@university.edu',
    password: 'student123',
    role: 'student',
    name: 'Bob Smith',
    avatar: 'https://via.placeholder.com/100?text=Bob',
  },
  {
    id: 'student-003',
    email: 'carol.white@university.edu',
    password: 'student123',
    role: 'student',
    name: 'Carol White',
    avatar: 'https://via.placeholder.com/100?text=Carol',
  },
  {
    id: 'student-004',
    email: 'david.brown@university.edu',
    password: 'student123',
    role: 'student',
    name: 'David Brown',
    avatar: 'https://via.placeholder.com/100?text=David',
  },
  {
    id: 'student-005',
    email: 'emily.davis@university.edu',
    password: 'student123',
    role: 'student',
    name: 'Emily Davis',
    avatar: 'https://via.placeholder.com/100?text=Emily',
  },
  {
    id: 'student-006',
    email: 'frank.miller@university.edu',
    password: 'student123',
    role: 'student',
    name: 'Frank Miller',
    avatar: 'https://via.placeholder.com/100?text=Frank',
  },
  // Parents
  {
    id: 'parent-001',
    email: 'parent1@email.com',
    password: 'parent123',
    role: 'parent',
    name: 'Mary Johnson',
    avatar: 'https://via.placeholder.com/100?text=Mary',
  },
  {
    id: 'parent-002',
    email: 'parent2@email.com',
    password: 'parent123',
    role: 'parent',
    name: 'Robert Smith',
    avatar: 'https://via.placeholder.com/100?text=Robert',
  },
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: 'student-001',
    studentId: '2024-001',
    name: 'Alice Johnson',
    email: 'alice.johnson@university.edu',
    enrolledDate: '2024-08-15',
  },
  {
    id: 'student-002',
    studentId: '2024-002',
    name: 'Bob Smith',
    email: 'bob.smith@university.edu',
    enrolledDate: '2024-08-15',
  },
  {
    id: 'student-003',
    studentId: '2024-003',
    name: 'Carol White',
    email: 'carol.white@university.edu',
    enrolledDate: '2024-08-20',
  },
  {
    id: 'student-004',
    studentId: '2024-004',
    name: 'David Brown',
    email: 'david.brown@university.edu',
    enrolledDate: '2024-08-18',
  },
  {
    id: 'student-005',
    studentId: '2024-005',
    name: 'Emily Davis',
    email: 'emily.davis@university.edu',
    enrolledDate: '2024-08-22',
  },
  {
    id: 'student-006',
    studentId: '2024-006',
    name: 'Frank Miller',
    email: 'frank.miller@university.edu',
    enrolledDate: '2024-08-17',
  },
];

export const MOCK_SUBJECTS: Subject[] = [
  {
    id: 'subject-001',
    code: 'CS101',
    name: 'Introduction to Programming',
    description: 'Fundamentals of programming using Python',
    schedule: 'MWF 9:00 AM - 10:00 AM',
    room: 'Room 201',
    semester: 'Spring 2026',
    enrolledStudents: ['student-001', 'student-002', 'student-003', 'student-005'],
    instructorId: 'inst-001',
    color: 'blue',
  },
  {
    id: 'subject-002',
    code: 'CS201',
    name: 'Data Structures & Algorithms',
    description: 'Advanced data structures and algorithm design',
    schedule: 'TTh 2:00 PM - 3:30 PM',
    room: 'Room 305',
    semester: 'Spring 2026',
    enrolledStudents: ['student-002', 'student-004', 'student-006', 'student-001'],
    instructorId: 'inst-001',
    color: 'purple',
  },
  {
    id: 'subject-003',
    code: 'CS301',
    name: 'Web Development',
    description: 'Frontend and Backend web development',
    schedule: 'MWF 2:00 PM - 3:00 PM',
    room: 'Room 102',
    semester: 'Spring 2026',
    enrolledStudents: ['student-001', 'student-003', 'student-005'],
    instructorId: 'inst-001',
    color: 'green',
  },
  {
    id: 'subject-004',
    code: 'CS401',
    name: 'Machine Learning',
    description: 'Introduction to ML algorithms',
    schedule: 'TTh 10:00 AM - 11:30 AM',
    room: 'Room 415',
    semester: 'Spring 2026',
    enrolledStudents: ['student-002', 'student-004', 'student-006'],
    instructorId: 'inst-002',
    color: 'red',
  },
];

export const MOCK_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    id: 'att-001',
    studentId: 'student-001',
    subjectId: 'subject-001',
    date: new Date('2026-02-23'),
    status: 'present',
    markedAt: new Date('2026-02-23T09:05:00'),
    markedBy: 'inst-001',
  },
  {
    id: 'att-002',
    studentId: 'student-002',
    subjectId: 'subject-001',
    date: new Date('2026-02-23'),
    status: 'late',
    markedAt: new Date('2026-02-23T09:15:00'),
    markedBy: 'inst-001',
    notes: 'Arrived 15 mins late',
  },
  {
    id: 'att-003',
    studentId: 'student-003',
    subjectId: 'subject-001',
    date: new Date('2026-02-23'),
    status: 'present',
    markedAt: new Date('2026-02-23T09:03:00'),
    markedBy: 'inst-001',
  },
  {
    id: 'att-004',
    studentId: 'student-001',
    subjectId: 'subject-002',
    date: new Date('2026-02-23'),
    status: 'present',
    markedAt: new Date('2026-02-23T14:05:00'),
    markedBy: 'inst-001',
  },
  {
    id: 'att-005',
    studentId: 'student-002',
    subjectId: 'subject-002',
    date: new Date('2026-02-23'),
    status: 'present',
    markedAt: new Date('2026-02-23T14:02:00'),
    markedBy: 'inst-001',
  },
];
